author: "Alfons Zelicko"
info: "Software, Design & D'n'D"
description: "My name is Alfons Zelicko, I am a software developer"
keywords: "alfons zelicko, alfons, zelicko"
favicon: "images/favicon.png"

social:
  - name: "Email"
    weight: 1
    url: "/contact"
    target: "_self"
  - name: "Github"
    weight: 2
    url: "https://github.com/alfonsZelicko"
    target: "_blank"
  - name: "LinkedIn"
    weight: 3
    url: "https://www.linkedin.com/in/alfons-zelicko-7a8645182/"
    target: "_blank"
  - name: "CV"
    weight: 4
    url: "/resume.pdf"
    target: "_blank"
