name: Build Resume PDF

on:
  push:
    branches:
      - main
    paths:
      - 'content/resume.md'
      - 'assets/styles/resume.pdf.css'
      - '.github/workflows/generate-pdf.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install md-to-pdf
        run: npm install -g md-to-pdf

      - name: Clean Markdown and Generate PDF
        run: |
          perl -0777 -pe 's/\+\+\+.*?\+\+\+\s*//s' content/resume.md > content/clean_resume.md
          md-to-pdf content/clean_resume.md --stylesheet assets/styles/resume.pdf.css --pdf-options '{ "format": "A4", "margin": "0", "printBackground": true }' --launch-options '{ "args": ["--no-sandbox"] }'
          rm content/clean_resume.md
          mv content/clean_resume.pdf static/resume.pdf

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: resume-pdf
          path: static/resume.pdf

      - name: Commit and Push PDF
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add static/resume.pdf
          git commit -m "docs: sync static resume pdf [skip ci]" || echo "No changes to commit"
          git push