name: Update Comment Stats
on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  update-json:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Fetch and Process Discussion Stats
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # 1. fetching data - now with reaction details
          gh api graphql -f query='
            query {
              repository(owner: "alfonsZelicko", name: "personal-website") {
                discussions(first: 100) {
                  nodes {
                    title
                    comments { totalCount }
                    reactions(first: 100) {
                      nodes { content }
                      totalCount
                    }
                  }
                }
              }
            }' > raw_data.json

          # 2. reaction grouping into flat json
          mkdir -p static
          cat raw_data.json | jq '.data.repository.discussions.nodes | 
            if . == null then {} else 
            reduce .[] as $item ({}; . + { 
              ($item.title): { 
                "comments": $item.comments.totalCount, 
                "reactions": $item.reactions.totalCount,
                "reaction_details": ($item.reactions.nodes | group_by(.content) | map({ (.[0].content): length }) | add)
              } 
            }) 
            end' > static/comments-stats.json

      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          # force add -> in case it is in .gitignore - yes, i did it O:-)
          git add -f static/comments-stats.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "chore: update comment stats" && git push)
